/* -*- Mode: C; indent-tabs-mode: t; c-basic-offset: 4; tab-width: 4 -*- */
/*
 * main.c - Auto-generated by Anjuta's Makefile project wizard
 * 
 */

#include<stdio.h>
#include"apue.h"
#include<dirent.h>

typedef struct dirent vivid;
int main(int argc,char *argv[])
{
	DIR *dp;
	vivid *dirp;
	if(argc != 2)
		err_quit("error");
	if((dp = opendir(argv[1]))==NULL)
		err_sys("error");
	while((dirp = readdir(dp))!= NULL)//自动递归遍历目录文件
		printf("%s\n",dirp->d_name);
	closedir(dp);
	return 0;
}